<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260328180704 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE guests (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nick_name VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, avatar_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4D11BCB286383B10 ON guests (avatar_id)');
        $this->addSql('ALTER TABLE guests ADD CONSTRAINT FK_4D11BCB286383B10 FOREIGN KEY (avatar_id) REFERENCES file (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE users ALTER created_at DROP DEFAULT');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE guests DROP CONSTRAINT FK_4D11BCB286383B10');
        $this->addSql('DROP TABLE guests');
        $this->addSql('ALTER TABLE users ALTER created_at SET DEFAULT \'now()\'');
    }
}
