<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260402220345 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE battle_players (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, lives INT NOT NULL, status VARCHAR(20) NOT NULL, score INT NOT NULL, tool_hint BOOLEAN NOT NULL, tool_eliminate BOOLEAN NOT NULL, tool_skip BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, battle_room_id INT NOT NULL, guest_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_ECD1F7C59E88C4F0 ON battle_players (battle_room_id)');
        $this->addSql('CREATE INDEX IDX_ECD1F7C59A4AA658 ON battle_players (guest_id)');
        $this->addSql('CREATE TABLE battle_rooms (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(20) NOT NULL, total_rounds INT NOT NULL, current_round INT NOT NULL, max_players INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, creator_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_659A4B2461220EA6 ON battle_rooms (creator_id)');
        $this->addSql('CREATE TABLE chat_messages (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content VARCHAR(255) NOT NULL, type VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, room_id INT NOT NULL, sender_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EF20C9A654177093 ON chat_messages (room_id)');
        $this->addSql('CREATE INDEX IDX_EF20C9A6F624B39D ON chat_messages (sender_id)');
        $this->addSql('ALTER TABLE battle_players ADD CONSTRAINT FK_ECD1F7C59E88C4F0 FOREIGN KEY (battle_room_id) REFERENCES battle_rooms (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE battle_players ADD CONSTRAINT FK_ECD1F7C59A4AA658 FOREIGN KEY (guest_id) REFERENCES guests (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE battle_rooms ADD CONSTRAINT FK_659A4B2461220EA6 FOREIGN KEY (creator_id) REFERENCES guests (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE chat_messages ADD CONSTRAINT FK_EF20C9A654177093 FOREIGN KEY (room_id) REFERENCES battle_rooms (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE chat_messages ADD CONSTRAINT FK_EF20C9A6F624B39D FOREIGN KEY (sender_id) REFERENCES guests (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE battle_players DROP CONSTRAINT FK_ECD1F7C59E88C4F0');
        $this->addSql('ALTER TABLE battle_players DROP CONSTRAINT FK_ECD1F7C59A4AA658');
        $this->addSql('ALTER TABLE battle_rooms DROP CONSTRAINT FK_659A4B2461220EA6');
        $this->addSql('ALTER TABLE chat_messages DROP CONSTRAINT FK_EF20C9A654177093');
        $this->addSql('ALTER TABLE chat_messages DROP CONSTRAINT FK_EF20C9A6F624B39D');
        $this->addSql('DROP TABLE battle_players');
        $this->addSql('DROP TABLE battle_rooms');
        $this->addSql('DROP TABLE chat_messages');
    }
}
