<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260421040231 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE game_session_guest (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, score INT NOT NULL, lives INT NOT NULL, is_alive BOOLEAN NOT NULL, game_session_id INT NOT NULL, guest_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DD2EBE888FE32B32 ON game_session_guest (game_session_id)');
        $this->addSql('CREATE INDEX IDX_DD2EBE889A4AA658 ON game_session_guest (guest_id)');
        $this->addSql('ALTER TABLE game_session_guest ADD CONSTRAINT FK_DD2EBE888FE32B32 FOREIGN KEY (game_session_id) REFERENCES game_session (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE game_session_guest ADD CONSTRAINT FK_DD2EBE889A4AA658 FOREIGN KEY (guest_id) REFERENCES guests (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE game_session_guest DROP CONSTRAINT FK_DD2EBE888FE32B32');
        $this->addSql('ALTER TABLE game_session_guest DROP CONSTRAINT FK_DD2EBE889A4AA658');
        $this->addSql('DROP TABLE game_session_guest');
    }
}
