<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260402202940 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE game_answers (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, operation VARCHAR(10) NOT NULL, correct BOOLEAN NOT NULL, time_ms INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, guest_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C512B9299A4AA658 ON game_answers (guest_id)');
        $this->addSql('ALTER TABLE game_answers ADD CONSTRAINT FK_C512B9299A4AA658 FOREIGN KEY (guest_id) REFERENCES guests (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE refresh_tokens ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE refresh_tokens ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER INDEX uniq_9bace7e1c05fb297 RENAME TO UNIQ_9BACE7E1C74F2195');
        $this->addSql('ALTER TABLE users ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE users ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE game_answers DROP CONSTRAINT FK_C512B9299A4AA658');
        $this->addSql('DROP TABLE game_answers');
        $this->addSql('ALTER TABLE refresh_tokens ALTER id SET DEFAULT nextval(\'refresh_tokens_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE refresh_tokens ALTER id DROP IDENTITY');
        $this->addSql('ALTER INDEX uniq_9bace7e1c74f2195 RENAME TO uniq_9bace7e1c05fb297');
        $this->addSql('ALTER TABLE users ALTER id SET DEFAULT nextval(\'users_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE users ALTER id DROP IDENTITY');
    }
}
